"""changed models

Revision ID: 3fbaef3d732a
Revises: 6a43d083a238
Create Date: 2025-06-20 21:33:43.265539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fbaef3d732a'
down_revision = '6a43d083a238'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rent_payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('period_start', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('period_end', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(
            'fk_rent_payments_tenant_id',  # Add explicit constraint name
            'tenants', 
            ['tenant_id'], 
            ['id']
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rent_payments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_rent_payments_tenant_id', type_='foreignkey')
        batch_op.drop_column('tenant_id')
        batch_op.drop_column('status')
        batch_op.drop_column('period_end')
        batch_op.drop_column('period_start')
    # ### end Alembic commands ###
