"""edited lease table

Revision ID: 546e001ed4c9
Revises: 3fbaef3d732a
Create Date: 2025-06-21 14:57:42.712269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '546e001ed4c9'
down_revision = '3fbaef3d732a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leases', schema=None) as batch_op:
        batch_op.alter_column('payment_due_day',
               existing_type=sa.DATE(),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leases', schema=None) as batch_op:
        batch_op.alter_column('payment_due_day',
               existing_type=sa.Integer(),
               type_=sa.DATE(),
               existing_nullable=False)

    # ### end Alembic commands ###
